### PR TITLE
[FSDE-13111] Improved radio button alignment

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-13111

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-297/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a39f0ddb3dfe81eaccbb6adc3a8971d82933d581-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-297-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-297/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2ada65e5601633d6e1c74274f9e2fa6c8f3449e6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-297-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-297/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1d0609596aeac4b3c9c0f9a04d5e9822cfdf0fdd-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-297-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-297/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-297/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://ecc268cabd79f8f012ed5e7e3c5cc80f4275c821-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-297-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by mattnickles — APPROVED** [review]

**Pull request merged**
