### PR TITLE
[FSDE-11802] Added support of Brightspeed theme compilation

### PR DESCRIPTION
**Pull request by janibolkvadze**
As a demo of the new theme compilation, I changed Checkbox component Checked state color to `indigo` in Brightspeed theme. So please open the PR instance Checkbox component page and change:
`<link rel="stylesheet" href="/chi.css" id="chi-css">`
to
`<link rel="stylesheet" href="/chi-brightspeed.css" id="chi-css">`
You should be able to see the checkbox checked state with the color `indigo`.

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-272/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b80e3babab30058147199eb71e6c4fc743b2663b-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-272-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by evansito — APPROVED** [review]

**Review by josecarlosgonzalezv — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-272/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-272/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b00a55a2cfd8e63cc6f0e94aa3eb1ddf7cd77c43-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-272-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by dani-cl-madrid** [comment]
@janibolkvadze , is there a way to update the documentation CSS file? I tried adding ?theme=Brightspeed to the URL but it didn't work. Apart from that, all the code looks good.

**Review by dani-cl-madrid — COMMENTED** [review]
@janibolkvadze, is there a way to update the documentation CSS file? I tried adding ?theme=Brightspeed to the URL but it didn't work. Apart from that, all the code looks good.

**Review by dani-cl-madrid — CHANGES_REQUESTED** [review]
@janibolkvadze, it would be good to make the GET param work, so the new theme can be shown, although this new theme should not be shown in the theme selector.

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-272/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://6b0cc57fb4aa0a9c4d9f32e3deb2d2c613c3fc45-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-272-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by mattnickles — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-272/6/. :white_check_mark:

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://90d27796a0f91400689d2dd060b887c168d8d7c2-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-272-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by dani-cl-madrid — APPROVED** [review]

**Pull request merged**
