### PR TITLE
[FSDE-12812] Fix Vulnerabilities Issues

### PR DESCRIPTION
**Pull request by julianatienza**

### CODE REVIEW

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-291/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5d9c829fe17b98316e7dace0294436dd98534f4a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-291-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
Removed the Hyperion allocated resources

**Comment by SCMAUTO** [comment]
Removed the Hyperion allocated resources

**Comment by SCMAUTO** [comment]
Removed the Hyperion allocated resources

**Pull request merged**
