### PR TITLE
[FSDE-1349] Added DevOpsGCR Enhancements and fixes

### PR DESCRIPTION
**Pull request by julianatienza**

### CODE REVIEW

**Comment by julianatienza** [comment]
@davisein  this PR will update the JSL release so CHI will have the requested changes in the attachment normalization besides some fixes and enhancements

**Review by jorgedelaflor — APPROVED** [review]
+1 hidding jslAdoptionStats in a try catch is preventing some checks to be effective.

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-121/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-121/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://da6c1f7647011e674f53b9924ada7e7e6f4e7703-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-121/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://ca3c4139c0171d99078434179ab04ba7352d7a68-chi-pr.enterprise.ctl.io

**Pull request merged**
