### PR TITLE
[FSDE-1123] Added support of chiRowSelected and chiRowDeselected events to Chi Vue Data Table component

### PR DESCRIPTION
**Pull request by janibolkvadze**
@dani-cl-madrid @SergioQCL @jllr 

https://ctl.atlassian.net/browse/FSDE-1204

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-111/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-111/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-111/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5dd98171d75800ff3064ca7267f23ab00f99254e-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-111/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5124aaa5dfcbdcf2560a2345c56fdedccd3d5665-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Review by dani-cl-madrid — APPROVED** [review]

**Review by SergioQCL — APPROVED** [review]
ACK

**Review by SergioQCL — APPROVED** [review]
LGTM

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-111/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f3a98a72107bdcc7ed65ed59a789a74430559dc3-chi-pr.enterprise.ctl.io

**Pull request merged**
