### PR TITLE
[FSDE-3099] Changed CTA style for portal themed links

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-3099

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-147/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://8ade109be534da8a1dbe830c7a6a5795993c4c4d-chi-pr.enterprise.ctl.io

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-147/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://6520dc27ccffa17c3a897f2ec46ed0defdfdc11f-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-147/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5c77a53c2af3a6bbcc9775ac8778a77675570d92-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-147/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a237228669a6af9ef767f18c9d9337b2320a117f-chi-pr.enterprise.ctl.io

**Review by aryaroudi — APPROVED** [review]

**Pull request merged**
