### PR TITLE
[FSPE-7772] Added support of formats to Date WC

### PR DESCRIPTION
**Pull request by janibolkvadze**
@SergioQCL 

- [x] Fixed formatting issue of Date wc
- [x] Improved User Input validation of Date Picker wc when using non-default format

https://ctl.atlassian.net/browse/FSPE-7772

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-41/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://d0141478d98625d67f4fff0033e184cfafa0e194-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-41/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-41/3/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-41/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c1a1f5a800bf586537b1357fe7e34c4da39be447-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-41/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e0f2ed39bffe3b4a2076730e36e041a3a2c4f7c6-chi-pr.enterprise.ctl.io

**Review by SergioQCL — APPROVED** [review]
LGTM

**Pull request closed without merging**
