### PR TITLE
[FSDE-16530] Data table complex add print function

### PR DESCRIPTION
**Pull request by josecarlosgonzalezv**
This pull request is created to test the `print` function in the **complex** example.

- Check if you can use the function in the generated instance without pop-up blockers in different browsers.

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-348/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4d6b09656e10e32074de6460fd043d2a232cd087-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-348-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-348/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a7c8bad5a8f2cfcca45f24e16a3739ecf70d22b7-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-348-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-348/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-348/5/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-348/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5747218959bcb960e29ec54e8741cf9809126058-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-348-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c33bc3919c8c1308c03f8c3d2252174dfe7e1bb5-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-348-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by janibolkvadze — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0cf7029b16b5bd318b15a33a6d7563026462cf03-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-348-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
