### PR TITLE
[DPEDE-1558] Investigate new format in Date Picker

### PR DESCRIPTION
**Pull request by xft-dev**
[https://ctl.atlassian.net/browse/DPEDE-1558](https://ctl.atlassian.net/browse/DPEDE-1558)

Problem: 

Typing new formats (e.g with **-** or **spaces**) in Date Picker input are not allowed and automatically the date introduced is removed.

Solution: 

In function `checkSingleDate` I change `isValid` function to non-strict in order to allow this types of format.

### CODE REVIEW

**Review by emerson-pereira — APPROVED** [review]

**Review by ASanchLumen — CHANGES_REQUESTED** [review]
It works well!! Can we add a test that types the date with both new formats (spaces and -)? It should test that the value of the component is correct or that the event chiDateChange is emitted with the correct value (see `expect(spy.getCall(0).args[0].detail).to.equal(dateTime);` date-picker.cy.js@603)

**Review by ASanchLumen — APPROVED** [review]
Test looks good and passes in local. Pipeline is failing though!

**Comment by xft-dev** [comment]
> Test looks good and passes in local. Pipeline is failing though!

In local, tests fail in `chiDateInvalid`

**Comment by ASanchLumen** [comment]
> > Test looks good and passes in local. Pipeline is failing though!
> 
> In local, tests fail in `chiDateInvalid`
> 
> image

@xft-dev  Indeed that test fails. The event is not emitted, and also it is not detecting that as an invalid date:

Original:

image


Type 14/02/2023 (which is incorrect, as format is MM/DD/YYYY) + enter:

image


It goes to 2 - feb - 2024 --> aka 14th month of 2023. This should be looked into, maybe it is caused by `strict = false` added in this PR.

**Review by ASanchLumen — CHANGES_REQUESTED** [review]
Left a comment...

To allow those formats, maybe we could take the direct approach and add them in `constants.ts` (if the cause is indeed the strict = false)

**Comment by xft-dev** [comment]
[https://github.com/CenturyLink/Chi/pull/1123/commits/fad9e49787ce06ddc29c9bda9e426ccefa5d2a39](https://github.com/CenturyLink/Chi/pull/1123/commits/fad9e49787ce06ddc29c9bda9e426ccefa5d2a39)

Errors in tests fixed. @ASanchLumen 

The purpose of the ticket is to allow hyphen format when an user types a date. I also add the space format because it would be useful.

**Review by josecarlosgonzalezv — APPROVED** [review]

**Comment by xft-dev** [comment]
[https://github.com/CenturyLink/Chi/pull/1123/commits/e517d6889f946c6b9ecce9d8de89abdc9d7fb96d](https://github.com/CenturyLink/Chi/pull/1123/commits/e517d6889f946c6b9ecce9d8de89abdc9d7fb96d)

Variable names changed. Ready to review @ASanchLumen @josecarlosgonzalezv

**Pull request merged**
