### PR TITLE
Chi-Vue Cypress + BackstopJS test implementation

### PR DESCRIPTION
**Pull request by sarmbrusterctl**

### CODE REVIEW

**Comment by jllr** [comment]
@sarmbrusterctl PR is not building because there are onflicts that need to be resolved. Can you solve them, please?

**Comment by sarmbrusterctl** [comment]
> @sarmbrusterctl PR is not building because there are onflicts that need to be resolved. Can you solve them, please?

@jllr conflicts resolved. Could you please try to review again? Thank you.

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-82/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://fe913054f6f446831656ae87c8461c1813eb1e64-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-82/5/. :x:

**Comment by jllr** [comment]
Chi Vue e2e test have been set up in another PRs

**Pull request closed without merging**
