### PR TITLE
[FSPE-7190] Added Centurylink theme

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-7190

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-36/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://fef4176855eed213dd645731236765cbc73f2c1c-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-36/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-36/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://043c3a4395b6a40218dbabc916db1fe55cdc11a8-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-36/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e3953348b5d3337659b707eb064c5cdcf83373c3-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-36/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://810cd008a5c25b21dbaca1bace0184b067eb72eb-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-36/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://db9f01ac4edabfa627e11f87c9e570bac4e54111-chi-pr.enterprise.ctl.io

**Review by janibolkvadze — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-36/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e6cee4e89cb2d406a37464dad05e06b181135ff2-chi-pr.enterprise.ctl.io

**Comment by jllr** [comment]
Awesome job @mattnickles!

**Pull request merged**
