### PR TITLE
[FSDE-7479] Create mobile modals component

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-7479

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-244/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://d3ad41f7f0aa75e3ce931b69af27b11f77eb6eec-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-244-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-244/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c8514916b56579a4edab622ab70e41f97b07c03b-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-244-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-244/3/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-244/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e9d4b1d4737098403202eadbbf4de8b2e45a4e4a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-244-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by evansito — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-244/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c4cc68d0516f5fd344734d89b3876b34fee90dc6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-244-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by mattnickles — APPROVED** [review]

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-244/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7021f67f81a8fa6ac30958ffa811573e44be449f-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-244-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-244/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b7b644855940869abd9f03d62fbe770f14932b14-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-244-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-244/9/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://3d53f85adc174e7d7f1920087b3a34b2f1484730-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-244-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
