### PR TITLE
[FSPE-7708] Prepare release for Chi 4.0.0

### PR DESCRIPTION
**Pull request by jllr**

### CODE REVIEW

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-38/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://cb7cd236ce0fc9bf9281ab2889c8a3b2fbf2aece-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-38/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1b6df015d1150ee7dcb14e001fadd58e2e1b19fb-chi-pr.enterprise.ctl.io

**Pull request merged**
