### PR TITLE
[FSDE-21008] Update dependencies to fix dependabot alerts

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-398/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-398/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-398/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://799ba6930a18176f9ad78f121f4f201c667047f2-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-398-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by josecarlosgonzalezv — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Pull request merged**
