### PR TITLE
[FSDE-1362] DevOpsGCR And Jira Deployments ChangeLog

### PR DESCRIPTION
**Pull request by julianatienza**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a6d3e2cad31cbff339e0129bf4ea6b3fab8fe833-chi-pr.enterprise.ctl.io

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1326d365be2f029c2237238b851e6b50ef05743d-chi-pr.enterprise.ctl.io

**Comment by julianatienza** [comment]
Hi guys. Any update about this Pull Request?

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://8703ee99f5c29f13eeae6d4e9a6f156e76654831-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e55ab652b2ae424c4f3579e183f5013b66aee74a-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/7/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://216eca671b743f00f6a545bd9fb1c45655223be4-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/9/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f21c50c0440388dabbb047af06c4b61f967aef63-chi-pr.enterprise.ctl.io

**Comment by julianatienza** [comment]
Updated to last version of Library

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/13/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://9ab9e7289fc65d929f7c9768182b10c51308cbbf-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/14/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f5de3302ee8c1255c53268e03737dcd5a4f0bb6e-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/15/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://6b884ad0ca4320a733a8472086e4701f7aa4e0aa-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/16/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b06b8ff74fa75019ae9b84fe60a4c702eb43b390-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/17/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e3caa12daff234a6838e39eaac699f2109305ee6-chi-pr.enterprise.ctl.io

**Review by jfranciscohernbal — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-143/18/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://37614abe6210b2fa2146aa3ff65211ccee74a3b4-chi-pr.enterprise.ctl.io

**Pull request merged**
