### PR TITLE
[FSDE-1356] Prepared Chi v5.0.0 release

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-1356

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-122/1/. :x:

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-122/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://74926211ae719bf4c6c0b0ae2683c3a8cc2f5168-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-122/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://00d1ddade7bae2788508bb0b727747253bf21a91-chi-pr.enterprise.ctl.io

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
