### PR TITLE
[FSDE-18099] Improve version check comparator

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-365/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-365/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://6275ea6d829024f420b117e1eeb4e4d45f5fa1a7-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-365-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by josecarlosgonzalezv — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-365/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b3f756f5402c4a305cb124fb68529e5bc63a55ac-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-365-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-365/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://d695e38acf5386fb6dd3b1477fad89c253866040-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-365-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
