### PR TITLE
[FSDE-11581] Prepare Chi 5.7.0 release

### PR DESCRIPTION
**Pull request by jllr**

### CODE REVIEW

**Review by josecarlosgonzalezv — APPROVED** [review]

**Review by evansito — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-264/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e2f549a95f07d666e5489624e9d8f869a9e839c7-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-264-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-264/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e2f549a95f07d666e5489624e9d8f869a9e839c7-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-264-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-264/3/. :white_check_mark:

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
