### PR TITLE
[FSDE-6041] Prepare Chi 5.4.0 release

### PR DESCRIPTION
**Pull request by jllr**

### CODE REVIEW

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-187/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://29a1a115a6b0729f757e9a7afdcac7d8fbe80d07-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-187/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://29a1a115a6b0729f757e9a7afdcac7d8fbe80d07-chi-pr.enterprise.ctl.io

**Review by aryaroudi — APPROVED** [review]

**Pull request merged**
