### PR TITLE
[FSDE-1430] Updated Lodash, Marked, PrismJS, Pug dependencies

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://118850ae71761360bbffb1d453f266330745f590-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7d56bae862929d168c9b20aca2fb9bd8e362d990-chi-pr.enterprise.ctl.io

**Comment by jllr** [comment]
@evansito @josecarlosgonzalezv please review

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0cc70a52e8b31307974752fbe6ccefa09942e3b3-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://ef1b1454876bec645b27aac8b2bf009e61c143a4-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0ed87e3914afd0999e73e26489f5d2fab76b4a8b-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/6/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c54b1188592f6e2a2a3ec6032d94ef442cc1649e-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c54b1188592f6e2a2a3ec6032d94ef442cc1649e-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/9/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/10/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7da246f455d8af28a05c94e7fc85028cc92ff9b4-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/11/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://43551aced7d245bf047ae68d6a336d1a7d16c750-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/12/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://13fe4b39336943e2cbf5d2ccdc24573db87da809-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/13/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://58c0ed71be61b163e8200dd42caf693f5a4a5920-chi-pr.enterprise.ctl.io

**Review by aryaroudi — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-130/14/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a370706ab78a653f14c8bca4b36475dc95d83d3d-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Pull request merged**
