### PR TITLE
[FSDE-17126] Update documentation typo error

### PR DESCRIPTION
**Pull request by soujanreddy**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-391/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://9ffe58d8f8fda23d3e22f2ce90816c41012a9843-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-391-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-391/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c8b2e2c4ae5286187c77301c0f73e027031aec24-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-391-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by josecarlosgonzalezv — APPROVED** [review]

**Pull request merged**
