### PR TITLE
[FSDE-2861] Added chat-outline and copy icon

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-2861

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-145/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7597166823e35426f89455266e0bfa35184b4ecd-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-145/2/. :x:

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-145/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://86e76d1676f77dce92ca9797b36a58e92e464582-chi-pr.enterprise.ctl.io

**Review by josecarlosgonzalezv — APPROVED** [review]

**Review by aryaroudi — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-145/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-145/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://718dd354f81947ce3ad29fa4a9e721e63bd5d60e-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-145/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://d75630fde0344656eacdabf4fe0bf3d98e3befe1-chi-pr.enterprise.ctl.io

**Pull request merged**
