### PR TITLE
[FSDE-17591] Added support of chiDateInvalid event emission

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-361/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-361/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-361/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f5596c6dfb79ce6be9c35bc896de6901724ad16b-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-361-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by SergioQCL — APPROVED** [review]

**Review by soujanreddy — APPROVED** [review]

**Review by josecarlosgonzalezv — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Pull request merged**
