### PR TITLE
[FSDE-306] Add html and css of toolbar

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-306

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://06897d4223210dc9bc08bb33942246bf49689d70-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://133b8574fd68b8ba7b6913fc9e6019ee31529ed5-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7f35f4bb58b1f3dc22b995d381b62fbbea86c89a-chi-pr.enterprise.ctl.io

**Review by mattnickles — COMMENTED** [review]
@jllr 👍  Looks great. Let's add `-primary` to the search icon button for consistency with the style guide.

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://8a6fc3e3990d9ca0d85f5eba3b5d61c6327c083d-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/8/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/9/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/12/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/13/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://14c296b3ceee853a70b4fb94d7f60e003d4c3539-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/14/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/15/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/16/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/19/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-67/20/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://918de8cade1b89e122802f4172dab965b8ce8dc4-chi-pr.enterprise.ctl.io

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
