### PR TITLE
[FSPE-7719] Added page title with breadcrumb portal template

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-7719

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-44/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://fe1f84179be030f9f30c0fbf05e3cca0c52b0309-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-44/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f8f1ccdb57b6bde0ca9a30eae15be6ce07460fd6-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-44/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c91ae5c9f518687601a7aeb60885730171998b64-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-44/5/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-44/6/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-44/8/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-44/9/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://9b0e78784122d144bc4af312c2824eeae22c8d5f-chi-pr.enterprise.ctl.io

**Pull request merged**
