### PR TITLE
[FSDE-1403] Added lib.lumen.com hostname to theme switcher

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-126/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c4176212a38dbd229585fea0b66317247bc91b77-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-126/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://45a43f75981b290d4daf1bda94aad683580bb352-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-126/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e52d88fad28ba81916a6a5a731ce9c6e9226c656-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-126/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://58b3f8bd29a60bc051a27839f1f85e96c5e2c5cc-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Review by aryaroudi — APPROVED** [review]

**Pull request merged**
