### PR TITLE
[FSDE-835] Created web component for microapp template

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-835

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-104/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-104/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2e4dd107863e6cb18cf804ef13d4d54e526b7e47-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-104/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://785a6ca85906e2169fe19d69fbe6732d9fb1a831-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-104/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-104/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://67edeac2414491212e1af545d4ad63d364171482-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2675713137d01fadbd1a5188e0b410c2d28f8129-chi-pr.enterprise.ctl.io

**Review by dani-cl-madrid — APPROVED** [review]

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
