### PR TITLE
[FSDE-2050] Enabled striping on Data Table examples

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/FSDE-2050

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-135/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://26f5f757e7850523b9d31628c1b1cd26d988edbd-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-135/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://53b77ca22797163a944083124146c401944b0013-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-135/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://93e18ad8b95c9ab4cdba0235044215d8a229b64c-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Comment by jllr** [comment]
@evansito @josecarlosgonzalezv can you review?

**Review by josecarlosgonzalezv — APPROVED** [review]

**Review by evansito — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-135/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f8fb7c5eaba49dba302fe9115cb400c1d3d2fdac-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-135/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://66bc678b220d5682ce707128bd17715e659209df-chi-pr.enterprise.ctl.io

**Review by mattnickles — APPROVED** [review]

**Pull request merged**
