### PR TITLE
[FSDE-20776] Fix sublevel row selection when selectionDisabled is set

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-396/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1c06d799aaccece634a81e7aa868f35a38d43b09-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-396-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-396/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in http://fe694db339053abba909de1c3aef887eb4987d71-chi-pr-po-ctl.s3-website-us-east-1.amazonaws.com (external) and in https://nginx-pr-396-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
