### PR TITLE
[FSDE-12325] Fix Carousel arrows & event emission

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-289/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://eeb2c041e71319458203a7c2644549fd10d6944b-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-289-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://ced27492b70a4067035211aba4598fcf1296a554-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-289-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-289/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c901e32a865487b9c79b8f7651c9b05d574d9917-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-289-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by evansito — APPROVED** [review]

**Pull request merged**
