### PR TITLE
[FSDE-7456] Make footer in App layout component stick to the bottom of the screen

### PR DESCRIPTION
**Pull request by josecarlosgonzalezv**
@evansito

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4a892afc92014e72bb8f02b20040b02c18f31b99-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/9/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://61706c6b181e4f890dbd0994624b3a518010c52b-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by evansito — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/10/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a8e69644c714ebbc2ff92ff5759607f5fffac7d6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/11/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/13/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://fc3e147754db954ab07c9215eeb78ea5c96fc9d6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/14/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f19173fc3607fd3e18bb52f47aea1f5413ee3db9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/15/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/16/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/17/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/18/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://9da89868a31948870853e7179858f75c8f683b37-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/19/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://12346f37cae7949adf1ced79a6d91d28a5c34af5-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/20/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://eb991d93ff1aa5bbc55b0f1cfcb3ba111f7ec433-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/21/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://3db0b2fcbcbe73b7177d3887e95ed7d06ae11624-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/22/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4b7e5cb31031d418527d9ad6dc7009b9c8651140-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/23/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/24/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/25/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/26/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://cab8bddb1931183c147be31cba95964c37505d27-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/27/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://164dd7f382ed983e595aee4dd4d181d666829d6b-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/28/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5e99ca5aa14507da51c0799236a9f0b6a81d5ba7-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/29/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://9922181aafe98aee2b3c6f6f5ee53988135fa93d-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/30/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://010a29e2c3c9a404529e56d8c61e54fa78aff06a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/31/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/33/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://bf28584b3c1f5a7a525a08d9ff4a30e79dffed3a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/34/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://17b31f7c33a4411b623a5524dde7257d334531e9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/35/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://48357a9a24eea15eaa022e2be49d1524a092eef6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/36/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b617ed101bd122eac1bde2882acb7dfee547c3de-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/37/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1c2481136ccf137cd459468fbb236e7411cc1be1-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/38/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://760c7a181153ae0c7141d809ee163464fec825c9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/39/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2b4c4973d1e71cb3816b94bf9c5a499910b66e20-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/40/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f84c86a8ecd8ec2e2621a673e689c085cc1d0c6a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/41/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://221243958417007f5911a58bcda96145688b9b19-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/42/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://ecbae0a822d95de57bc5c8cbbb3b5db07cd6a247-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/43/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/44/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/45/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://8f0cf318c75b03a4e49da3631c8fe7beacc522f6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/46/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://646f1413f59c77778de7e0a62aa13d4c1276125d-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/47/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/48/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1eede834c75d43cb502f99af5c9d78864271970d-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/50/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/51/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e86b404dca56f3a787ce79fff6f03761d2fdf63c-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/52/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://137742653029e2aa99c54fd7d18b4dc22f33a6c3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7b6d6323d2ba765ed0adca8e7e91cd278bf4c227-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/54/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://cc18f05dcf06444310b164f96bce116ac2d6ca51-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/55/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://65c1818ea5f2202fcb2c39dead53b7a3e7542d9a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/56/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/57/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://6144a746b2b273e912396d2809958d5975ea5c20-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/58/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://99de13f1c0a5599ff8034e78e8d78b3292193cfa-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/59/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f1d2a122367e8adf6ab3b36bbd731c76abbe1264-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-215/60/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4d802685bb0d07e216c84df3a9cc5f102931cd7d-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-215-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request closed without merging**
