### PR TITLE
[FSDE-12389] Added support of switching docs to Brightspeed theme

### PR DESCRIPTION
**Pull request by janibolkvadze**
With these changes, adding `?theme=Brightspeed` to documentation page URLs should enable the Brightspeed theme

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-278/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-278/2/. :x:

**Review by jllr — APPROVED** [review]

**Review by dani-cl-madrid — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-278/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://caf40efd40f71b9f85b0ed734d3e4eaa168f7b75-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-278-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-278/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://be5dd64029e9eebebf96e8d391ca642cdd6ea7a2-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-278-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-278/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7e665c53c0be9fec5ba501fcce02d35b0517c424-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-278-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-278/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5ed2a0ea3e3fda18e234028d7ca69b482f7fc142-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-278-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
