### PR TITLE
[FSDE-18572] Added support for widget cards

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-18572

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-373/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b7976a3dd8747849c8609af42ca49260df4eacb9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-373-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-373/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f6a21ac3596cbf6730566e8e6ae13a312fe870c3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-373-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-373/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-373/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in http://993009f4d58c678508fdfdb902fcb708d7c8990b-chi-pr-po-ctl.s3-website-us-east-1.amazonaws.com (external) and in https://nginx-pr-373-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-373/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in http://184c7772eb7d3a82c7b429575765413f4534a14a-chi-pr-po-ctl.s3-website-us-east-1.amazonaws.com (external) and in https://nginx-pr-373-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-373/9/. :white_check_mark:

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
