### PR TITLE
[FSDE-699] Improved Popover open on hover examples

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/FSDE-699

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-60/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://cdb4ac6f2b80f219443860962f75c7a8f1caee54-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Review by mattnickles — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-60/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://53ba78815f2ce6c88c26a952ec54c5bd65dbb6ca-chi-pr.enterprise.ctl.io

**Pull request merged**
