### PR TITLE
[FSDE-19988] Add support of conditional base url for different env

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/5/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/7/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/8/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/9/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://35cead3532afc06d7ba18052c2e97e0adb604f16-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-386-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/10/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/11/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2024b6bf2cd5f833e86a3ec5cd0afb99e1a819ef-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-386-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/12/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/13/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://07bf69ffdd0559bed47dc9379f05d43efbf804d6-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-386-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/14/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/16/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://36e2657cbbe2d352108067b239c43ea1c1a5ce6e-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-386-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b7f781eb732ea4140a35d1ec4a82a2c514e790de-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-386-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/18/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://90a03f86404547c9326fa418e88eba7fb94c48b0-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-386-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/19/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/21/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/25/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/26/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/28/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://ff8b73e990e1e7557c1b67e3cc6279c6b30e4abe-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-386-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by josecarlosgonzalezv — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-386/32/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1cc03eb585f22f2a0964f0d5c929c85d70adb522-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-386-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
