### PR TITLE
[FSDE-3126] Added support of chiColumnsReset event emission

### PR DESCRIPTION
**Pull request by janibolkvadze**
### Commir summary

- [x] Added `chiColumnsReset` and `chiToolbarColumnsReset` events' emission
- [x] Fixed Pagination issue in scenarios of updating data from `no rows` to having rows

https://ctl.atlassian.net/browse/FSDE-3126

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-149/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://3d647d2732164f59babda2093330e87e35126ef1-chi-pr.enterprise.ctl.io

**Review by cristb — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-149/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://79cfb18a814a2fe7dfbb518f37b37aec6184dc1b-chi-pr.enterprise.ctl.io

**Review by aryaroudi — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-149/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4f8c0b5d8bdf5bb7cbba1c6939cbb19be324f33d-chi-pr.enterprise.ctl.io

**Pull request merged**
