### PR TITLE
[FSDE-9633] Prepare Chi 5.6.0 release

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-9633

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-226/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-226/2/. :x:

**Review by janibolkvadze — APPROVED** [review]

**Review by josecarlosgonzalezv — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-226/3/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-226/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-226/6/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-226/7/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-226/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2edda38469a9c45e640a9e5778baec5fb8e05538-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-226-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
