### PR TITLE
[FSDE-3406] Fixed sonar duplicate selectors and missing aria labels

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-3406

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-151/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f8f24f8d90693eaaabd60d4b608b2da5fd8697cb-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-151/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f03312d22386037fe8dec4060d94f8ac899c5672-chi-pr.enterprise.ctl.io

**Review by aryaroudi — APPROVED** [review]

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
