### PR TITLE
[FSDE-4892] Fix Copy btn size in code snippets

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-4892

### CODE REVIEW

**Review by mattnickles — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-175/1/. :x:

**Review by dani-cl-madrid — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-175/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://01fae0392364a05c94b9261d34c3d6a5d02301de-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-175/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://dfaad8f059631f7fb493d96ae107d518ac8090d9-chi-pr.enterprise.ctl.io

**Pull request merged**
