### PR TITLE
[FSDE-19374] Added support for new solid tab variants

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-19374

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-385/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0f54b6851dabc044f8c4f796151da60b938c9236-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-385-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-385/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-385/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c56e9d891ef91bfcbfa5fa7df49325a66d538773-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-385-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-385/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://df8f16f9bf37dbc0d483fa7431705dc01deaa2ac-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-385-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
