### PR TITLE
[FSPE-7772] Added support of formatting of Date WC

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-48/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://6d5377c7486961a3684f28361c025ce58eea9349-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-48/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-48/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0c2e79c7c9db8f4395548c1c98b90ca9d780c18d-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Pull request merged**
