### PR TITLE
[FSDE-18643] Prepare Chi 5.13.0 release

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-376/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://494fcc5c5e523810e1636ef49ad3cc8710c8ffbb-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-376-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-376/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://8b6dcb95a4a44c05b61fb72bde8a73fef0dec4a8-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-376-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by josecarlosgonzalezv — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-376/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1cfcc32c09c91a8ae142b6d7e55caf2fa83fa045-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-376-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by jllr — APPROVED** [review]

**Pull request merged**
