### PR TITLE
Revert "[FSDE-6414] Adding auto prs (#239)"

### PR DESCRIPTION
**Pull request by robersantamaria**
This reverts commit 9f2925aeb49f2ab6c605b97ef34ad5a7d602ac63.

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-313/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-313/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-313/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5bdcbdfa1647b20c1f05b04b32a4d5eaadbadf80-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-313-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by janibolkvadze — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Pull request merged**
