### PR TITLE
[FSDE-650] Add support of pending state in steps component

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-650

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-54/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://49d460b9258eb8d6727fdb54887e135764f56495-chi-pr.enterprise.ctl.io

**Review by mattnickles — CHANGES_REQUESTED** [review]
Looks like the root issue is the steps component is dependent on there being an -active class present. This can be addressed without the addition of a pending class by making the base step item style inactive/pending instead of active.

**Comment by mattnickles** [comment]
Solved in #56

**Pull request closed without merging**
