### PR TITLE
[FSPE-7720] Changed portal card styles

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-7720

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-46/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://664f2b33e52ff7c34718cd30569b878a46f2c404-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-46/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-46/3/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-46/6/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-46/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://02cd6105b7a2f1b4eeb138a987d995131265c9f2-chi-pr.enterprise.ctl.io

**Pull request merged**
