### PR TITLE
[FSDE-10976] Fixed Data Table activePage issue

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-251/1/. :x:

**Review by evansito — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-251/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-251/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://02a28dae44eaf16f8b245ba3dd284161ae9ea5a3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-251-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
