### PR TITLE
[FSDE-10897] Update footer links

### PR DESCRIPTION
**Pull request by soujanreddy**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-253/1/. :x:

**Comment by evansito** [comment]
Are all centurylinks meant to be replaced? I can see some links such as https://www.lumen.com/en-us/contact-us.html or https://www.centurylink.com/business/login/ etc that redirect to lumen. Otherwise this LGTM

**Review by evansito — COMMENTED** [review]
Are all centurylinks meant to be replaced? I can see some links such as https://www.lumen.com/en-us/contact-us.html or https://www.centurylink.com/business/login/ etc that redirect to lumen. Otherwise this LGTM

**Comment by soujanreddy** [comment]
> Are all centurylinks meant to be replaced? I can see some links such as https://www.lumen.com/en-us/contact-us.html or https://www.centurylink.com/business/login/ etc that redirect to lumen. Otherwise this LGTM

@evansito Only a couple of links related to Gender Gap and Modern Slavery needs to be updated as per the requirement.

**Comment by evansito** [comment]
> > Are all centurylinks meant to be replaced? I can see some links such as https://www.lumen.com/en-us/contact-us.html or https://www.centurylink.com/business/login/ etc that redirect to lumen. Otherwise this LGTM
> 
> @evansito Only a couple of links related to Gender Gap and Modern Slavery needs to be updated as per the requirement.

Approved then 😃

**Review by evansito — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-253/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4c61b67d4c54f0329d1e96ca4dc85df0004a612a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-253-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by mattnickles — APPROVED** [review]

**Review by janibolkvadze — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Pull request merged**
