### PR TITLE
[FSDE-676] Update child and grand child data table background color

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-676

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-55/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5cd30384a48807445b1db3fa19b484ad21c6e706-chi-pr.enterprise.ctl.io

**Review by mattnickles — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-55/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-55/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2a7489c55dd0390b7f6dc4e34d571a743cb5051d-chi-pr.enterprise.ctl.io

**Pull request merged**
