### PR TITLE
[FSDE-1401] Changed portal drawer close icon color

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-1401

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-125/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://8b60834149119694f51f80c7182adc022dff5063-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-125/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://9f7110cca15ff06f34d2f1e8879585bcc7b7d09c-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-125/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e86cf072d00c57cde08cdef43ad93b9b82e21fe4-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
