### PR TITLE
[FSDE-19751] Added support of combined deployment of both docs

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://001c0d8524e66cc8f1cf1140ca290f9948747f52-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-382-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://001c0d8524e66cc8f1cf1140ca290f9948747f52-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-382-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4fc2a5d981179d4c15bafb1cda6d5cbe413c1132-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-382-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b6ec7a3024f0b50112f4eab636e7b9a1fefbc589-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-382-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/6/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/7/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://dfee9718d1f6061e22f38c4235eea67b82a4486e-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-382-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/9/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/10/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/11/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/12/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline has run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-382/15/. :white_check_mark:

**Review by jllr — APPROVED** [review]

**Review by josecarlosgonzalezv — APPROVED** [review]

**Pull request merged**
