### PR TITLE
[FSDE-10070] Fixed Drawer component close button issue

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-236/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4a2048cd7fc85968de438fbee6a261e30bfe64d3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-236-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by evansito — APPROVED** [review]

**Review by aryaroudi — APPROVED** [review]

**Review by josecarlosgonzalezv — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-236/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://ca656373341b959cc822b2a0c1934fedeb17fd01-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-236-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
