### PR TITLE
[FSDE-11221] Changed stat component design for portal theme

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-11221

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-255/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://bdbd0386ac0244b7fb16b74ccf7d42de9edbcd4d-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-255-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-255/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0a6a9a3694579e44187e530f4a39b5ddd8398e27-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-255-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-255/5/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-255/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1278f23ee05d13611195c6752c6672df9789719a-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-255-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by jllr — APPROVED** [review]

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
