### PR TITLE
[FSDE-19725] Fixed text wrapping in data table popovers

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-19725

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-381/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://1330d0a65979a7b02b264eb38dfab5e24ca1d274-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-381-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by janibolkvadze — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-381/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5b3f9e2042e63f63e1ea876504eafe832d577520-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-381-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
