### PR TITLE
[FSDE-3822] QualityGate1 Integration

### PR DESCRIPTION
**Pull request by julianatienza**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-186/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://cdd8b8f8931c502f530a8b69daf0f76a3c5e277c-chi-pr.enterprise.ctl.io

**Comment by julianatienza** [comment]
Reported stat: 
https://github.com/CenturyLink/jsl-pipeline-maturity-level-reports/tree/master/UX-CHI/Productive/Chi/PR-186/QualityGateReport

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-186/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://05c514abced7f2d97237366dc08a58d87af0138c-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-186/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5ae615ba3bfe22d034e6953bf364546d42dd47bb-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-186/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://3d7e795d867020220df9e7ac50a05a444717276a-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-186/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://d6f2402b44d26098b37f0a26e0db98488505df13-chi-pr.enterprise.ctl.io

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
