### PR TITLE
[FSDE-16767] Added icons to form input error messages

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-16767

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-353/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-353/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://dac11550f76a7ba1a2b6c34b97753a4993ef5530-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-353-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by jllr — APPROVED** [review]

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-353/5/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-353/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0e6f7858a0e2fb6c115382c2a172860cd8993888-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-353-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
