### PR TITLE
[FSDE-12323] Added support of Pagination to Carousel

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-316/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://ae5f3fb84b7e76f8432f67c4cade0ded8c4a290e-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-316-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f60120d4a4b39a524374ff03f11a96b1a70f97f3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-316-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by jllr — APPROVED** [review]

**Review by mattnickles — COMMENTED** [review]
Is there a way to vertically center the pagination prev/next button relative to the content instead of the total height of the carousel?

image

**Review by mattnickles — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-316/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://210c392671d943ed30f5e2dffd319ace94b581db-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-316-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by janibolkvadze** [comment]
> Is there a way to vertically center the pagination prev/next button relative to the content instead of the total height of the carousel?
> 
> image

Yep, I will see if I can get that aligned relative to the content. Thanks!

**Pull request merged**
