### PR TITLE
[FSDE-8499] Prepare for Lumen org rename

### PR DESCRIPTION
**Pull request by robersantamaria**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/7/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/9/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://3565ba7550bca935f3b7a2e687ed33d499ab1363-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c10164b2a55e2808759b0762af3357c6db905efa-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/11/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://402e6405a74806604097b1fb19efde9ca1bd0206-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/12/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c64b97476624b8d7968c35d8389672995d50f833-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/13/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://121c23b53ea7cfff11154349c4c573846c42a07f-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/14/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://af450d42c6d436baa5213611e41adbaa4b00bcb9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/15/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://911464a21186c59b09d481bcfb0779aad7706733-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/16/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2f6d6d686cf746cfefa8e6909699b5c680495a8f-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/17/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://5413a4ddc786d89dc6ff9ae99347842c451794ba-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://37f1814e86c9b2e1158d463d5fbbaf36dae850f0-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/19/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://71a78282e6f3ac444cac2565e2805534cccda686-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/21/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/22/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://54baa5563c8e32ec77519daa0ab717f19125befe-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/23/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b0c3204a0d9768b2fc7908db01de5bab15fd2ca5-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by robersantamaria** [comment]
@janibolkvadze @jllr please take a look, this is ready.

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/24/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0b20eb5c11f0498ac001d58f1719ae888b3fefc9-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/25/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://62b05e6fde3477de493ef905ba7c28af350e3406-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/26/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7ccb69c29df259ba830226b2e0cc5ea9cae79045-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by janibolkvadze — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Review by julianatienza — APPROVED** [review]

**Comment by julianatienza** [comment]
@jllr  please, do an squash and merge to preserve the Jira Id in the  merge commit. Thanks!!!

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-217/27/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a2645b969196a3f1cdc19b25278421a8bacbeb22-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-217-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
