### PR TITLE
[FSDE-3062] Added support for no underline on hover to link component

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-3062

### CODE REVIEW

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-146/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://456ab38bf6d77e6a6faf3be92db1144fdd073b11-chi-pr.enterprise.ctl.io

**Review by aryaroudi — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-146/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://c68801b31bc19d34f8c97cfc435d619ed77da7fc-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-146/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://48d1501cece73c4c99d9db730327fc2dd2d76bda-chi-pr.enterprise.ctl.io

**Pull request merged**
