### PR TITLE
[FSDE-936] Update release and increase retries

### PR DESCRIPTION
**Pull request by julianatienza**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-265/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://53640a6aebbc167d12d4d5def009341e8f6f0c03-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-265-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by dani-cl-madrid — APPROVED** [review]

**Review by janibolkvadze — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-265/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-265/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://534059ef8a443af4d93e63fad9f7b22274872d14-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-265-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-265/4/. :x:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://cd841492d3d854dff924e89ec6ae25caab9ab9df-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-265-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
