### PR TITLE
[FSDE-939] Added support of HTML Select multiple for Column Customization sub-module of Data Table

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-74/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4127e593127747334d849bba7e1bf5dcd9be33ac-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-74/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://23e914f4e492615c8f91349a42c6b767f9535b50-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-74/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2ccd41cc4c4ba7409361d100b04d9bfa37b739ed-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-74/3/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-74/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-74/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://bca28e859756470075a6153bcbd5689bf81104cd-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Pull request merged**
