### PR TITLE
[FSDE-8984] Fallback update

### PR DESCRIPTION
**Pull request by julianatienza**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-256/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://f5bee23e06b95ef563a48556cfe341dc0cf467cd-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-256-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by janibolkvadze — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-256/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://09a9b07b2f6f8942a0629ae3c9a6538b6da9e843-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-256-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-256/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://30a93cfbb80e531c4d1a515907749910ec2f1269-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-256-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Pull request merged**
