### PR TITLE
[FSPE-7717] Changed navigation styles

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-7717

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-40/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7e484673f0923fe50b1f9f4307eaa54ba77e8862-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-40/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://e5bd715f4a889a4d636cad24aa9c7b2c33fdd86b-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Pull request merged**
