### PR TITLE
[FSDE-13113] Fix prune job

### PR DESCRIPTION
**Pull request by julianatienza**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-295/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a5be0a4358888aaf0e45c70a856c89716064727f-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-295-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/chi-garbage-collector/job/PR-295/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/chi-garbage-collector/job/PR-295/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-295/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/chi-garbage-collector/job/PR-295/4/. :white_check_mark:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/chi-garbage-collector/job/PR-295/5/. :white_check_mark:

**Review by jfranciscohernbal — APPROVED** [review]

**Review by jorgedelaflor — APPROVED** [review]
+1

**Review by jllr — APPROVED** [review]

**Pull request merged**
