### PR TITLE
[FSDE-13112] Fix generating SRI SHAs

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/3/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0e4b9e1637f7a17925191ced2ce760625a34cc34-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-298-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0e4b9e1637f7a17925191ced2ce760625a34cc34-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-298-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a786fc451fd9bab2af03a18de744b0e6335abae3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-298-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://63f5235a0298708932b009b6437b8504a828d847-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-298-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/9/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/10/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/11/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/12/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b461872e952b1858bc16ae009c273ef079d2d0b3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-298-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/13/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b461872e952b1858bc16ae009c273ef079d2d0b3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-298-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/14/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/15/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-298/16/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://b74b57dbbb786fcebe347381cc71f0d0d5cfdbd3-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-298-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Review by jfranciscohernbal — APPROVED** [review]

**Review by julianatienza — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Pull request merged**
