### PR TITLE
[FSPE-7409] Add support of Chi Vue CDN distribution

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/FSDE-300

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://9f2b58fc9f813b89051abd8e69f5579478169a20-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4dd01b759645e81c0a22b5d742ffa25393ccd5d0-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://4c4819c93ef5e1df045312838e174003bd81e2a0-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/6/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://cc0322775bf6727798d2dba3b9827c0595436c2f-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://46648a71ee953bf3037afde7d33c18d29b5b9341-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a28f07ee6dbb417775d4c33b06d8b2ba5255772f-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/9/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/10/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/12/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://22ff54fbf126974facc473e1820e70300f2abd02-chi-pr.enterprise.ctl.io

**Review by jfranciscohernbal — APPROVED** [review]

**Review by dani-cl-madrid — APPROVED** [review]

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://45848739a6f1a8f44bba0b3ccbe05deb254748f2-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/14/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://3f245a237943f2f5a6f5c888b3bd0364a001791c-chi-pr.enterprise.ctl.io

**Comment by janibolkvadze** [comment]
@jllr @mattnickles Can you review the PR, please? Mostly `data-table/_examples.pug` to see:
1. The approach of including Vue and Chi Vue
2. Definition and usage of Vue components

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/16/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/18/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://3d2a0d4f8064210ad00306233c6eff9c8a90eadf-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/19/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://26652360f326d7197e34929dcabf4249dcbd6f6f-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/20/. :x:

**Review by mattnickles — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-49/21/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://3397bce3abd11ba67b6822ee3ebf26c1e20ff0de-chi-pr.enterprise.ctl.io

**Pull request merged**
