### PR TITLE
[FSDE-12678] Added full set of full-color and one-color marketing icons

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-12678

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-288/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7cc317d967f7b2f5febbc0008f7a4d6b0bcffe61-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-288-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-288/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2037ef47092a9e27b9de8194691f59e64c2b53bb-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-288-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-288/3/. :x:

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-288/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-288/5/. :x:

**Review by jllr — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-288/6/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-288/7/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-288/8/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://7c27912e29445e3dc482b0289ca05596ca4a1abd-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-288-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-288/9/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://2e91f5d98ca3865dbe5ac1abf7dc5fb506356175-chi-pr.enterprise.ctl.io (external) and in https://nginx-pr-288-ux-chi.kubeodc-test.corp.intranet/ (internal)

**Comment by SCMAUTO** [comment]
Removed the Hyperion allocated resources

**Comment by SCMAUTO** [comment]
Removed the Hyperion allocated resources

**Comment by SCMAUTO** [comment]
Removed the Hyperion allocated resources

**Pull request merged**
