### PR TITLE
[FSDE-1099] Removed localhost:8000 from Cypress tests

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/FSDE-1099

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-95/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://ad301899150479bf1731d7591a5eccbb13b1dd26-chi-pr.enterprise.ctl.io

**Review by julianatienza — APPROVED** [review]
Thanks!!! It Looks Good to me. 

Please, can you merge this PR after resolving conflicts?

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-95/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://be8b5aec6eecb7d842013610c059a11a2a6af2e4-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Pull request merged**
