### PR TITLE
[FSDE-4432] Prepare Chi 5.3.0 release

### PR DESCRIPTION
**Pull request by jllr**

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-170/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://525fddb746774e8965f548e03bc8c981a24cf186-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-170/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://616cc3b6593e3057c3bdab5e5d88f6a2444c20ac-chi-pr.enterprise.ctl.io

**Review by cristb — APPROVED** [review]

**Review by dani-cl-madrid — APPROVED** [review]

**Review by robersantamaria — APPROVED** [review]

**Pull request merged**
