### PR TITLE
[FSDE-1381] Fixed dropdown menu item font-weight inherit bug

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSDE-1381

### CODE REVIEW

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-124/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://917e7092ac17e58fdc3612a6cd46f8dc2ee60ced-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-124/2/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://abe674fff6dbe84ddba40c85eb7fd824d71c6975-chi-pr.enterprise.ctl.io

**Review by jllr — APPROVED** [review]

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
