### PR TITLE
[FSDE-1172] Prepared Chi 4.4.0 release

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-1172

### CODE REVIEW

**Review by aryaroudi — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-108/1/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-108/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-108/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://0568181b34b52290dc9379dd2edc1699d518e9b7-chi-pr.enterprise.ctl.io

**Review by janibolkvadze — APPROVED** [review]

**Pull request merged**
