### PR TITLE
[FSDE-1060] Added white-space property to tooltip component

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSDE-1060

### CODE REVIEW

**Review by janibolkvadze — APPROVED** [review]

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-87/1/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://49844c6c55fb4e20677a004e4384d4830684c8d8-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-87/2/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-87/3/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://97dc1607bfbdb899a60bbc19a96270a446283760-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-87/4/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-87/5/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://09589c6ce463145b2ce9ca6c36718bd7505ea62f-chi-pr.enterprise.ctl.io

**Comment by SCMAUTO** [comment]
The CI pipeline did not run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-87/6/. :x:

**Comment by SCMAUTO** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Productive/job/Chi/job/PR-87/7/. :white_check_mark:

**Comment by SCMAUTO** [comment]
You can check this PRs instance in https://a10e427cdfb0fd06ec02256c380373610ca3767f-chi-pr.enterprise.ctl.io

**Review by mattnickles — APPROVED** [review]

**Pull request merged**
